package synapse

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/gorilla/websocket"
)

// ─── Interface ────────────────────────────────────────────────────────────────

// ChatStreamCase provides access to the bidirectional chat WebSocket.
//
// The stream sends messages to an agent and receives, on the same connection,
// the send confirmations (accepted/error), the agent replies and the execution
// events of the session conversations. Delivery envelopes are acknowledged
// automatically by the SDK, and the stream reconnects keeping the same session.
// A master (SYSTEM_ADMIN) token can chat with any agent; a tenant token can
// chat only with its own tenant's agents.
type ChatStreamCase interface {
	// Stream opens the chat WebSocket and keeps it alive, reconnecting
	// automatically with the same session until ctx is cancelled or the
	// returned stream is closed.
	Stream(ctx context.Context, opts *ChatStreamOptions) (*ChatStream, error)
}

// ─── Options and DTOs ─────────────────────────────────────────────────────────

// ChatStreamOptions tunes the chat stream. All fields are optional.
type ChatStreamOptions struct {
	// Session (UUID) resumes the same server-side delivery queue across
	// reconnections. Defaults to a random UUID kept for the stream lifetime.
	Session string

	// Buffer is the capacity of the accepted/messages/events channels
	// (default 256).
	Buffer int

	// OnConnect, when set, is invoked every time the WebSocket handshake
	// succeeds — on the first connection and on every automatic reconnection.
	OnConnect func(session string)

	// OnError, when set, is invoked with connection/decoding errors. The
	// stream keeps reconnecting regardless; this is for observability only.
	OnError func(error)
}

// ChatStreamAttachment is a file attached to a chat message.
type ChatStreamAttachment struct {
	URL      string `json:"url"`
	Type     string `json:"type"` // "image" | "audio" | "document"
	MimeType string `json:"mime_type,omitempty"`
	FileName string `json:"file_name,omitempty"`
}

// ChatStreamMessage is a chat message exchanged over the stream.
//
// Outbound (Send): UUID is generated by the SDK when empty, AgentUUID and
// Message are required; ConversationUUID, Context and Attachment are optional.
//
// Inbound (Messages): carries the agent reply — JobID, ConversationUUID,
// AgentUUID, AgentName, Message and, when present, Attachment. When Error is
// set, the job failed with a terminal error and Message is empty.
type ChatStreamMessage struct {
	UUID             string                `json:"uuid,omitempty"`
	JobID            string                `json:"job_id,omitempty"`
	AgentUUID        string                `json:"agent_uuid"`
	AgentName        string                `json:"agent_name,omitempty"`
	ConversationUUID string                `json:"conversation_uuid,omitempty"`
	Message          string                `json:"message"`
	Context          string                `json:"context,omitempty"`
	Attachment       *ChatStreamAttachment `json:"attachment,omitempty"`

	// Error is set when the job failed with a terminal error (e.g. agent not
	// found); in that case Message is empty.
	Error string `json:"error,omitempty"`
}

// ChatStreamAccepted is the server confirmation for a sent message frame.
// Error is set (instead of Status) when the server rejects the frame.
type ChatStreamAccepted struct {
	UUID   string `json:"uuid"`
	JobID  string `json:"job_id,omitempty"`
	Status string `json:"status,omitempty"` // "queued" | "throttled"
	Error  string `json:"error,omitempty"`
}

// chatSendFrame is the client → server message frame. The inner payload omits
// the frame UUID, which lives at the envelope level.
type chatSendFrame struct {
	Type    string `json:"type"` // "message"
	UUID    string `json:"uuid"`
	Message struct {
		AgentUUID        string                `json:"agent_uuid"`
		ConversationUUID string                `json:"conversation_uuid,omitempty"`
		Message          string                `json:"message"`
		Context          string                `json:"context,omitempty"`
		Attachment       *ChatStreamAttachment `json:"attachment,omitempty"`
	} `json:"message"`
}

// chatFrame is the server → client frame, covering all inbound types:
// "accepted"/"error" (send confirmations, no ACK) and the "message"/"event"
// delivery envelopes (acknowledged automatically by the SDK).
type chatFrame struct {
	Type    string             `json:"type"`
	UUID    string             `json:"uuid"`
	SentAt  time.Time          `json:"sent_at"`
	JobID   string             `json:"job_id,omitempty"`
	Status  string             `json:"status,omitempty"`
	Error   string             `json:"error,omitempty"`
	Message *ChatStreamMessage `json:"message,omitempty"`
	Event   *AgentEvent        `json:"event,omitempty"`
}

// ─── ChatStream ───────────────────────────────────────────────────────────────

// ChatStream is a live bidirectional chat WebSocket. Send messages with Send
// and consume Accepted(), Messages() and Events(); the channels are closed
// after Close() or context cancellation.
type ChatStream struct {
	accepted chan ChatStreamAccepted
	messages chan ChatStreamMessage
	events   chan AgentEvent
	session  string
	cancel   context.CancelFunc

	// mu guards conn (the currently active connection, nil when reconnecting).
	mu   sync.Mutex
	conn *websocket.Conn

	// writeMu serialises frame writes: Send runs on caller goroutines while
	// the read loop writes the envelope ACKs.
	writeMu sync.Mutex

	// pending tracks sent frame UUIDs until the server confirms them.
	pendingMu sync.Mutex
	pending   map[string]struct{}
}

// Send transmits a message to an agent. A version 4 UUID is generated when
// msg.UUID is empty; the frame is tracked as pending until the server confirms
// it on Accepted(). There is no client-side queue: when the stream is
// disconnected Send returns ErrStreamNotConnected immediately and the caller
// is responsible for resending. Send is safe for concurrent use.
func (s *ChatStream) Send(msg ChatStreamMessage) error {
	if msg.UUID == "" {
		uuid, err := randomUUID()
		if err != nil {
			return fmt.Errorf("synapse/chatstream.Send: generate message uuid: %w", err)
		}
		msg.UUID = uuid
	}

	s.mu.Lock()
	conn := s.conn
	s.mu.Unlock()
	if conn == nil {
		return ErrStreamNotConnected
	}

	var frame chatSendFrame
	frame.Type = "message"
	frame.UUID = msg.UUID
	frame.Message.AgentUUID = msg.AgentUUID
	frame.Message.ConversationUUID = msg.ConversationUUID
	frame.Message.Message = msg.Message
	frame.Message.Context = msg.Context
	frame.Message.Attachment = msg.Attachment

	// Track as pending before writing so a fast confirmation never arrives
	// before the registration.
	s.pendingMu.Lock()
	s.pending[msg.UUID] = struct{}{}
	s.pendingMu.Unlock()

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	_ = conn.SetWriteDeadline(time.Now().Add(wsWriteWait))
	if err := conn.WriteJSON(frame); err != nil {
		s.dropPending(msg.UUID)
		return fmt.Errorf("synapse/chatstream.Send: %w", err)
	}
	return nil
}

// Accepted returns the channel where send confirmations are delivered —
// both "accepted" (Status set) and "error" (Error set) frames.
func (s *ChatStream) Accepted() <-chan ChatStreamAccepted { return s.accepted }

// Messages returns the channel where agent replies are delivered.
func (s *ChatStream) Messages() <-chan ChatStreamMessage { return s.messages }

// Events returns the channel where execution events of the session
// conversations are delivered (same AgentEvent as the monitor stream).
func (s *ChatStream) Events() <-chan AgentEvent { return s.events }

// Session returns the session UUID used to resume the delivery queue.
func (s *ChatStream) Session() string { return s.session }

// Close stops the stream and closes the channels.
func (s *ChatStream) Close() { s.cancel() }

// setConn swaps the active connection (nil while reconnecting).
func (s *ChatStream) setConn(conn *websocket.Conn) {
	s.mu.Lock()
	s.conn = conn
	s.mu.Unlock()
}

// dropPending removes a sent frame UUID from the pending set.
func (s *ChatStream) dropPending(uuid string) {
	s.pendingMu.Lock()
	delete(s.pending, uuid)
	s.pendingMu.Unlock()
}

// ack writes the delivery acknowledgement for an envelope UUID, serialised
// with the Send writes.
func (s *ChatStream) ack(conn *websocket.Conn, uuid string) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	_ = conn.SetWriteDeadline(time.Now().Add(wsWriteWait))
	return conn.WriteJSON(wsAck{Type: "ok", UUID: uuid})
}

// ─── Implementation ───────────────────────────────────────────────────────────

type chatStreamClient struct {
	http *httpClient
}

func newChatStreamClient(hc *httpClient) ChatStreamCase {
	return &chatStreamClient{http: hc}
}

func (c *chatStreamClient) Stream(ctx context.Context, opts *ChatStreamOptions) (*ChatStream, error) {
	if opts == nil {
		opts = &ChatStreamOptions{}
	}

	session := opts.Session
	if session == "" {
		var err error
		session, err = randomUUID()
		if err != nil {
			return nil, fmt.Errorf("synapse/chatstream.Stream: generate session: %w", err)
		}
	}

	wsURL, err := c.http.buildWSURL(pathChatStreamWS, session)
	if err != nil {
		return nil, fmt.Errorf("synapse/chatstream.Stream: %w", err)
	}

	buffer := opts.Buffer
	if buffer <= 0 {
		buffer = wsDefaultBuffer
	}

	streamCtx, cancel := context.WithCancel(ctx)
	stream := &ChatStream{
		accepted: make(chan ChatStreamAccepted, buffer),
		messages: make(chan ChatStreamMessage, buffer),
		events:   make(chan AgentEvent, buffer),
		session:  session,
		cancel:   cancel,
		pending:  make(map[string]struct{}),
	}

	go c.run(streamCtx, stream, wsURL, opts.OnConnect, opts.OnError)
	return stream, nil
}

// run keeps the stream alive: dial, consume, and reconnect with backoff until
// the context is cancelled. The same session resumes the server queue.
func (c *chatStreamClient) run(ctx context.Context, stream *ChatStream, wsURL string, onConnect func(string), onError func(error)) {
	defer close(stream.accepted)
	defer close(stream.messages)
	defer close(stream.events)

	report := func(err error) {
		if onError != nil && err != nil {
			onError(err)
		}
	}

	backoff := wsBackoffMin
	for {
		if ctx.Err() != nil {
			return
		}

		conn, err := c.http.dialWS(ctx, wsURL)
		if err != nil {
			report(fmt.Errorf("synapse/chatstream: connect: %w", err))
		} else {
			stream.setConn(conn)
			if onConnect != nil {
				onConnect(stream.session)
			}
			backoff = wsBackoffMin
			err = c.consume(ctx, conn, stream)
			stream.setConn(nil)
			_ = conn.Close()
			if ctx.Err() != nil {
				return
			}
			report(fmt.Errorf("synapse/chatstream: connection lost: %w", err))
		}

		select {
		case <-ctx.Done():
			return
		case <-time.After(backoff):
		}
		backoff *= 2
		if backoff > wsBackoffMax {
			backoff = wsBackoffMax
		}
	}
}

// consume reads frames until the connection drops: send confirmations are
// delivered to Accepted() (no ACK), while message/event envelopes are
// acknowledged and delivered to Messages()/Events().
func (c *chatStreamClient) consume(ctx context.Context, conn *websocket.Conn, stream *ChatStream) error {
	prepareWSConn(conn)

	// Unblock the read loop as soon as the context is cancelled.
	done := make(chan struct{})
	defer close(done)
	go func() {
		select {
		case <-ctx.Done():
			_ = conn.Close()
		case <-done:
		}
	}()

	for {
		_, data, err := conn.ReadMessage()
		if err != nil {
			return err
		}
		_ = conn.SetReadDeadline(time.Now().Add(wsReadWait))

		var frame chatFrame
		if err := json.Unmarshal(data, &frame); err != nil {
			continue
		}

		switch frame.Type {
		case "accepted", "error":
			// Send confirmation: direct reply to a sent frame, no ACK.
			stream.dropPending(frame.UUID)
			confirmation := ChatStreamAccepted{
				UUID:   frame.UUID,
				JobID:  frame.JobID,
				Status: frame.Status,
				Error:  frame.Error,
			}
			select {
			case stream.accepted <- confirmation:
			case <-ctx.Done():
				return ctx.Err()
			}
		case "message":
			if frame.Message == nil {
				continue
			}
			// Acknowledge this envelope; without the "ok" the server retries.
			if err := stream.ack(conn, frame.UUID); err != nil {
				return err
			}
			select {
			case stream.messages <- *frame.Message:
			case <-ctx.Done():
				return ctx.Err()
			}
		case "event":
			if frame.Event == nil {
				continue
			}
			if err := stream.ack(conn, frame.UUID); err != nil {
				return err
			}
			select {
			case stream.events <- *frame.Event:
			case <-ctx.Done():
				return ctx.Err()
			}
		}
	}
}
